theme: jekyll-theme-cayman
title: HemoChek
description: An app to lower the risk of the spread of COVID-19 and hypercoagulation of patients

## Welcome to HemoChek

Thousands right now are suffering from the results of COVID-19 right now. HemoChek is here to protect doctor and patients from the spread of COVID-19.

We use a duo hemolyser through our app to give doctors a real-time blood tracker for their patients saving lives while slowing the spread.

### Markdown

Markdown is a lightweight and easy-to-use syntax for styling your writing. It includes conventions for

```markdown
Syntax highlighted code block

# Header 1
## Header 2
### Header 3

- Bulleted
- List

1. Numbered
2. List

**Bold** and _Italic_ and `Code` text

[Link](url) and ![Image](src)
```

For more details see [GitHub Flavored Markdown](https://guides.github.com/features/mastering-markdown/).

### Jekyll Themes

Your Pages site will use the layout and styles from the Jekyll theme you have selected in your [repository settings](https://github.com/19hollowayc/19hollowayc.github.io/settings). The name of this theme is saved in the Jekyll `_config.yml` configuration file.

### Support or Contact

Having trouble with Pages? Check out our [documentation](https://docs.github.com/categories/github-pages-basics/) or [contact support](https://support.github.com/contact) and we’ll help you sort it out.

